spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/foodBooking
    username: user
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  flyway:
    baseline-on-migrate: true
    url: jdbc:postgresql://localhost:5432/foodBooking
    user: user
    password: password